# Generated by Django 5.2 on 2026-08-15 02:13

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='servicos', variations={'thumb': {'crop': True, 'height': 216, 'width': 471}})),
                ('icone', models.CharField(max_length=80)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
