# Generated by Django 5.2 on 2026-08-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicos',
            new_name='Servico',
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
