# Generated by Django 5.2 on 2026-08-22 01:43

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_servicos_servico_alter_servico_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('foto', stdimage.models.StdImageField(force_min_size=False, upload_to='colaboradores', variations={})),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('coordenador', 'Coordenador'), ('jornalista', 'Jornalista'), ('fotografo', 'Fotógrafo(a)'), ('designer', 'Designer')], max_length=11)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
    ]
