# Generated by Django 5.2 on 2026-09-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
